### ISSUE TITLE
One failed test

### ISSUE THREAD

**Issue by efrapp** [fatymahmed/private-events#2]
When I run the tests one of them is failing:

```
user creates event successfully with valid information
     Failure/Error: click_button('Submit')

     Capybara::ElementNotFound:
       Unable to find button "Submit" that is not disabled
```

**Comment by KaushikShivam** [comment]
Dear @efrapp,
My partner and I have fixed the failing test. We were just working on improving the UI after submitting for the review :D
Please check the updated test.
Thanks
